setwd("matern_samples_ex/")
set.seed(10)
locs = cbind(seq(0, 1, .001), 1)
tau = GpGp::fast_Gp_sim(locs = locs, covfun_name = "matern15_isotropic", m = 10, covparms = c(3, .05, 0))
w = GpGp::fast_Gp_sim(locs = locs, covfun_name = "matern15_isotropic", m = 10, covparms = c(3, .005, 0))
pdf("noise.pdf", height=  4)
par(mar = c(2,2,.1,.1))
plot(locs[,1], sqrt(exp(tau))*rnorm(nrow(locs)), ylab = expression(epsilon), xlab = "s")
dev.off()
pdf("mar_var.pdf", height=  4)
par(mar = c(2,2,.1,.1))
plot(locs[,1], sqrt(exp(tau))*w, ylab = expression(epsilon), xlab = "s")
dev.off()
